services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"


  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./pkg/prometheus:/etc/prometheus
      - prom_data:/prometheus

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  prom_data:
