services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
      prometheus:
        condition: service_started
      redis:
        condition: service_started

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shrinkr
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 4s
      timeout: 2s
      retries: 5

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./pkg/prometheus:/etc/prometheus
      - prom_data:/prometheus

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  prom_data:
  db_data:
