version: "3.8"

services:
  backend:
    build: .
    expose:
      - "3001:3001"
    depends_on:
      - prometheus
      - redis
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9091:9090"
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  prom_data:
