export const urls = [
  {
    id: 1,
    url: "https://super-long-link.com/shorten-it",
    shortenedUrl: "shrink",
    totalClicks: 100,
    expiry: "2025-05-02",
    rateRemaining: 20,
    isActive: true,
  },
  {
    id: 2,
    url: "https://nextjs.org/docs/app/building-your-application/routing/pages",
    shortenedUrl: "next",
    totalClicks: 100,
    expiry: "2014-05-02",
    rateRemaining: 20,
    isActive: true,
  },
  {
    id: 3,
    url: "https://nextjs.org/docs/app/building-your-application/routing/pages",
    shortenedUrl: "next",
    totalClicks: 100,
    expiry: "2014-05-02",
    rateRemaining: 20,
    isActive: true,
  },
  {
    id: 4,
    url: "https://nextjs.org/docs/app/building-your-application/routing/pages",
    shortenedUrl: "next",
    totalClicks: 100,
    expiry: "2014-05-02",
    rateRemaining: 20,
    isActive: true,
  },
];
